### ISSUE TITLE
Chef cooking problem

### ISSUE THREAD

**Issue by AntoineReneleau** [gauntlt/gauntlt-starter-kit#6]
I'm having the same issue on ubuntu and OS X. Chef won't install correctly. Since I don't know how it works, I can't fix it.
Here's the output :
```
[...]
==> default: Running provisioner: chef_solo...
    default: Installing Chef (latest)...
Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2015-01-20T10:06:13+00:00] INFO: Forking chef instance to converge...
==> default: [2015-01-20T10:06:13+00:00] INFO: *** Chef 12.0.3 ***
==> default: [2015-01-20T10:06:13+00:00] INFO: Chef-client pid: 1561
==> default: [2015-01-20T10:06:15+00:00] INFO: Setting the run_list to ["recipe[vagrant_main]"] from CLI options
==> default: [2015-01-20T10:06:15+00:00] INFO: Run List is [recipe[vagrant_main]]
==> default: [2015-01-20T10:06:15+00:00] INFO: Run List expands to [vagrant_main]
==> default: [2015-01-20T10:06:15+00:00] INFO: Starting Chef Run for precise32
==> default: [2015-01-20T10:06:15+00:00] INFO: Running start handlers
==> default: [2015-01-20T10:06:15+00:00] INFO: Start handlers complete.
==> default: [2015-01-20T10:06:15+00:00] ERROR: Running exception handlers
==> default: [2015-01-20T10:06:15+00:00] ERROR: Exception handlers complete
==> default: [2015-01-20T10:06:15+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-01-20T10:06:15+00:00] ERROR: Cookbook loaded at path(s) [/tmp/vagrant-chef/c2db65b7cfb23ffaec9c3e7ae3a80cff/cookbooks/vagrant_main] has invalid metadata: The `name' attribute is required in cookbook metadata
==> default: [2015-01-20T10:06:15+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

Am I doing something wrong or is that a problem with the starter kit?

**Comment by antagonismorg** [comment]
I am receiving the same issue. Below is the output of the chef-stacktrace.out

Generated at 2015-01-28 20:07:10 +0000
Chef::Exceptions::MetadataNotValid: Cookbook loaded at path(s) [/tmp/vagrant-chef/1b6d5c05233db989c42ef3a9b89e4d02/cookbooks/git] has invalid metadata: The `name' attribute is required in cookbook metadata
/opt/chef/embedded/apps/chef/lib/chef/cookbook/cookbook_version_loader.rb:190:in `raise_metadata_error!'
/opt/chef/embedded/apps/chef/lib/chef/cookbook/cookbook_version_loader.rb:79:in `load'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:83:in `block in load_cookbook'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:82:in `each'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:82:in `load_cookbook'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:72:in `block in load_cookbooks'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:71:in `each'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:71:in `load_cookbooks'
/opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:61:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:235:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:397:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:245:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:224:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:40:in `load'
/usr/bin/chef-solo:40:in `<main>'

**Comment by apolloclark** [comment]
Interesting, when I run "vagrant up" on my machines, I see Chef 10.14.2 running successfully. My hosts are: Windows 7 64-bit, and a Mac 10.9.5, both running VirtualBox 4.3.20.

Neither of my hosts has Ruby, nor Chef installed. Do either of your hosts have Ruby and Chef installed?

**Comment by apolloclark** [comment]
My guess.... your individual Vagrant instances are using the latest version of Chef, installed on your Host.

http://stackoverflow.com/questions/11325479/how-to-control-the-version-of-chef-that-vagrant-uses-to-provision-vms

http://stackoverflow.com/questions/21274437/vagrant-install-chef-client-on-top-of-base-image

Easiest quick fix: add the "name" metadata entry manually to the cookbook .rb files. Long-term fix would be to update the Gauntlt-Starter-Kit Vagrant config to manually define which Chef-solo version it uses.

**Comment by apolloclark** [comment]
Any updates?

**Comment by AntoineReneleau** [comment]
Sorry, I didn't have time to work on this.
I tried to downgrade Chef with omnibus but it just put a warning on my Vagrantfile and didn't work. Then, I tried to add a name on each metadata.rb (folder name) and it didn't work either.
Here's the output : 

```
There were warnings and/or errors while loading your Vagrantfile
for the machine 'default'.

Your Vagrantfile was written for an earlier version of Vagrant,
and while Vagrant does the best it can to remain backwards
compatible, there are some cases where things have changed
significantly enough to warrant a message. These messages are
shown below.

Warnings:
* Unknown configuration section 'omnibus'. If this section was part of
a Vagrant 1.0.x plugin, note that 1.0.x plugins are incompatible with 1.1+.


Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'precise32'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: gauntlt_default_1423143753641_59809
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3000 => 3030 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 4.3
==> default: Mounting shared folders...
    default: /vagrant => /Users/areneleau/www/gauntlt/vagrant/gauntlt
    default: /tmp/vagrant-chef/323a2e67f56d0f8b7f12bc88ebb89b28/cookbooks => /Users/areneleau/www/gauntlt/vagrant/gauntlt/cookbooks
    default: /tmp/vagrant-chef/7693ce734c7ef1eb3e2ce227799eab47/cookbooks => /Users/areneleau/www/gauntlt/vagrant/gauntlt/site-cookbooks
==> default: Running provisioner: chef_solo...
    default: Installing Chef (latest)...
Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2015-02-05T13:49:21+00:00] INFO: Forking chef instance to converge...
==> default: [2015-02-05T13:49:21+00:00] INFO: *** Chef 12.0.3 ***
==> default: [2015-02-05T13:49:21+00:00] INFO: Chef-client pid: 1579
==> default: [2015-02-05T13:49:35+00:00] INFO: Setting the run_list to ["recipe[vagrant_main]"] from CLI options
==> default: [2015-02-05T13:49:35+00:00] INFO: Run List is [recipe[vagrant_main]]
==> default: [2015-02-05T13:49:35+00:00] INFO: Run List expands to [vagrant_main]
==> default: [2015-02-05T13:49:35+00:00] INFO: Starting Chef Run for precise32
==> default: [2015-02-05T13:49:35+00:00] INFO: Running start handlers
==> default: [2015-02-05T13:49:35+00:00] INFO: Start handlers complete.
==> default: [2015-02-05T13:49:35+00:00] WARN: MissingCookbookDependency:
==> default: Recipe `build-essential` is not in the run_list, and cookbook 'build-essential'
==> default: is not a dependency of any cookbook in the run_list.  To load this recipe,
==> default: first add a dependency on cookbook 'build-essential' in the cookbook you're
==> default: including it from in that cookbook's metadata.
==> default:
==> default: ================================================================================
==> default: Recipe Compile Error in /tmp/vagrant-chef/7693ce734c7ef1eb3e2ce227799eab47/cookbooks/vagrant_main/recipes/default.rb
==> default: ================================================================================
==> default:
==> default:
==> default: NoMethodError
==> default: -------------
==> default: undefined method `[]' for nil:NilClass
==> default:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef/323a2e67f56d0f8b7f12bc88ebb89b28/cookbooks/build-essential/recipes/default.rb:22:in `from_file'
==> default:
==> default:   /tmp/vagrant-chef/7693ce734c7ef1eb3e2ce227799eab47/cookbooks/vagrant_main/recipes/default.rb:5:in `from_file'
==> default:
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef/323a2e67f56d0f8b7f12bc88ebb89b28/cookbooks/build-essential/recipes/default.rb:
==> default:
==> default:
==> default:
==> default:  15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
==> default:
==> default:  16:  # See the License for the specific language governing permissions and
==> default:  17:  # limitations under the License.
==> default:  18:  #
==> default:  19:
==> default:  20:  require 'chef/shell_out'
==> default:  21:
==> default:  22>> compiletime = node['build_essential']['compiletime']
==> default:  23:
==> default:  24:  case node['os']
==> default:  25:  when "linux"
==> default:  26:
==> default:  27:    # on apt-based platforms when first provisioning we need to force
==> default:  28:    # apt-get update at compiletime if we are going to try to install at compiletime
==> default:  29:    if node['platform_family'] == "debian"
==> default:  30:      execute "apt-get update" do
==> default:  31:        action :nothing
==> default:
==> default: [2015-02-05T13:49:35+00:00] ERROR: Running exception handlers
==> default: [2015-02-05T13:49:35+00:00] ERROR: Exception handlers complete
==> default: [2015-02-05T13:49:35+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-02-05T13:49:35+00:00] ERROR: undefined method `[]' for nil:NilClass
==> default: [2015-02-05T13:49:35+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

Any idea?
Thanks for your help

**Comment by apolloclark** [comment]
What is your configuration?
OS, OS Version, 32/64-bit
Virtualbox version
Virtualbox Guest Extensions version
Vagrant version
Vagrant Omnibus version
Host Ruby version
Host Chef version

**Comment by AntoineReneleau** [comment]
OS X Yosemite 10.10.2
Virtualbox 4.3.20 r96996
Guest Additions Version: 4.2.0
Vagrant 1.7.2
vagrant-omnibus (1.4.1)
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
Chef not installed

**Comment by apolloclark** [comment]
Ok, I've upgraded my Macbook Air to the same specs you have, and have gotten the project working. I've created a pull request here:
https://github.com/gauntlt/gauntlt-starter-kit/pull/7

**Comment by AntoineReneleau** [comment]
It works ! Thanks a lot !

**Comment by apolloclark** [comment]
Nice! Glad to hear. I'll do a Youtube video soon showing how to set this up, run Railgots and Gruyere, then attack it with Gauntlt.

**Comment by apolloclark** [comment]
Changes have been updated, closing issue.
