### ISSUE TITLE
gauntlt-starter-kit out of sync. arachni now wants ruby 2.0.0

### ISSUE THREAD

**Issue by ambled** [gauntlt/gauntlt-starter-kit#8]
I realize there is a VirtualBox update, which I'll attempt tomorrow, however I do not expect that to solve the issue...

At the bottom of the trace you'll see that arachni now wants ruby >=2.0.0 rather than 1.9.3-r484

I'll try to set time aside tomorrow to iterate and do a PR if I figure it out, but I wanted to share in case someone else has the issue before it's resolved.

VirtualBox: 4.3.20 r96996
Vagrant: 1.7.2
OSX 10.9.5

workspace/gauntlt-starter-kit/vagrant/gauntlt ambled$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/trusty64'
    default: URL: https://atlas.hashicorp.com/ubuntu/trusty64
==> default: Adding box 'ubuntu/trusty64' (v20150512.0.1) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20150512.0.1/providers/virtualbox.box
==> default: Successfully added box 'ubuntu/trusty64' (v20150512.0.1) for 'virtualbox'!
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: gauntlt_default_1432163705579_11549
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3000 => 3030 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /Users/garth/workspace/gauntlt-starter-kit/vagrant/gauntlt
    default: /tmp/vagrant-chef/44bc2231dd852313d77b201ce66da0b1/cookbooks => /Users/garth/workspace/gauntlt-starter-kit/vagrant/gauntlt/cookbooks
    default: /tmp/vagrant-chef/9f0a5a37352ff7848058be768a28347a/cookbooks => /Users/garth/workspace/gauntlt-starter-kit/vagrant/gauntlt/site-cookbooks
==> default: Running provisioner: chef_solo...
    default: Installing Chef (latest)...
Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2015-05-20T23:16:21+00:00] INFO: Forking chef instance to converge...
==> default: [2015-05-20T23:16:21+00:00] INFO: **\* Chef 12.3.0 ***
==> default: [2015-05-20T23:16:21+00:00] INFO: Chef-client pid: 2510
==> default: [2015-05-20T23:16:27+00:00] INFO: Setting the run_list to ["recipe[build-essential]", "recipe[apt]", "recipe[git]", "recipe[vagrant_main]"] from CLI options
==> default: [2015-05-20T23:16:27+00:00] INFO: Run List is [recipe[build-essential], recipe[apt], recipe[git], recipe[vagrant_main]]
==> default: [2015-05-20T23:16:27+00:00] INFO: Run List expands to [build-essential, apt, git, vagrant_main]
==> default: [2015-05-20T23:16:27+00:00] INFO: Starting Chef Run for vagrant-ubuntu-trusty-64
==> default: [2015-05-20T23:16:27+00:00] INFO: Running start handlers
==> default: [2015-05-20T23:16:27+00:00] INFO: Start handlers complete.
==> default: [2015-05-20T23:16:28+00:00] WARN: Cloning resource attributes for apt_package[ruby1.9.1-dev] from prior resource (CHEF-3694)
==> default: [2015-05-20T23:16:28+00:00] WARN: Previous apt_package[ruby1.9.1-dev]: /tmp/vagrant-chef/9f0a5a37352ff7848058be768a28347a/cookbooks/vagrant_main/recipes/default.rb:11:in `block in from_file'
==> default: [2015-05-20T23:16:28+00:00] WARN: Current  apt_package[ruby1.9.1-dev]: /tmp/vagrant-chef/9f0a5a37352ff7848058be768a28347a/cookbooks/vagrant_main/recipes/default.rb:27:in`block in from_file'
==> default: [2015-05-20T23:16:44+00:00] INFO: apt_package[build-essential] installed build-essential at 11.6ubuntu6
==> default: [2015-05-20T23:16:51+00:00] INFO: apt_package[binutils-doc] installed binutils-doc at 2.24-5ubuntu3.1
==> default: [2015-05-20T23:17:00+00:00] INFO: apt_package[autoconf] installed autoconf at 2.69-6
==> default: [2015-05-20T23:17:07+00:00] INFO: apt_package[flex] installed flex at 2.5.35-10.1ubuntu2
==> default: [2015-05-20T23:17:14+00:00] INFO: apt_package[bison] installed bison at 2:3.0.2.dfsg-2
==> default: [2015-05-20T23:17:14+00:00] INFO: directory[/var/cache/local] created directory /var/cache/local
==> default: [2015-05-20T23:17:14+00:00] INFO: directory[/var/cache/local] owner changed to 0
==> default: [2015-05-20T23:17:14+00:00] INFO: directory[/var/cache/local] group changed to 0
==> default: [2015-05-20T23:17:14+00:00] INFO: directory[/var/cache/local] mode changed to 644
==> default: [2015-05-20T23:17:14+00:00] INFO: directory[/var/cache/local/preseeding] created directory /var/cache/local/preseeding
==> default: [2015-05-20T23:17:14+00:00] INFO: directory[/var/cache/local/preseeding] owner changed to 0
==> default: [2015-05-20T23:17:14+00:00] INFO: directory[/var/cache/local/preseeding] group changed to 0
==> default: [2015-05-20T23:17:14+00:00] INFO: directory[/var/cache/local/preseeding] mode changed to 644
==> default: [2015-05-20T23:17:25+00:00] INFO: apt_package[git-core] installed git-core at 1:1.9.1-1ubuntu0.1
==> default: [2015-05-20T23:17:32+00:00] INFO: apt_package[ruby1.9.1-dev] installed ruby1.9.1-dev at 1.9.3.484-2ubuntu1.2
==> default: [2015-05-20T23:17:39+00:00] INFO: apt_package[libxml2-dev] installed libxml2-dev at 2.9.1+dfsg1-3ubuntu4.4
==> default: [2015-05-20T23:17:39+00:00] INFO: apt_package[libxslt-dev] is a virtual package, actually acting on package[libxslt1-dev]
==> default: [2015-05-20T23:17:47+00:00] INFO: apt_package[libxslt-dev] installed libxslt-dev at (none)
==> default: [2015-05-20T23:17:56+00:00] INFO: apt_package[nmap] installed nmap at 6.40-0.2ubuntu1
==> default: [2015-05-20T23:18:09+00:00] INFO: apt_package[w3af-console] installed w3af-console at 1.1svn5547-1
==> default: [2015-05-20T23:18:25+00:00] INFO: apt_package[libcurl4-openssl-dev] installed libcurl4-openssl-dev at 7.35.0-1ubuntu2.5
==> default: [2015-05-20T23:18:32+00:00] INFO: apt_package[libsqlite3-dev] installed libsqlite3-dev at 3.8.2-1ubuntu2
==> default: [2015-05-20T23:18:39+00:00] INFO: apt_package[libyaml-dev] installed libyaml-dev at 0.1.4-3ubuntu3.1
==> default: [2015-05-20T23:18:46+00:00] INFO: apt_package[python-setuptools] installed python-setuptools at 3.3-1ubuntu1
==> default:
==> default: ================================================================================
==> default: Error executing action `run` on resource 'execute[install gems]'
==> default: ================================================================================
==> default:
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default: ------------------------------------
==> default: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of /usr/bin/ruby -S gem install gauntlt bundler arachni ----
==> default: STDOUT: Building native extensions.  This could take a while...
==> default: Building native extensions.  This could take a while...
==> default: Building native extensions.  This could take a while...
==> default: Successfully installed builder-3.2.2
==> default: Successfully installed diff-lcs-1.2.5
==> default:
==> default: Successfully installed multi_json-1.11.0
==> default: Successfully installed gherkin-2.12.2
==> default: Successfully installed multi_test-0.1.2
==> default: Successfully installed cucumber-1.3.15
==> default: Successfully installed ffi-1.9.8
==> default: Successfully installed childprocess-0.5.6
==> default: Successfully installed rspec-support-3.2.2
==> default: Successfully installed rspec-expectations-3.2.1
==> default: Successfully installed aruba-0.5.4
==> default: Successfully installed mini_portile-0.5.3
==> default: Successfully installed nokogiri-1.6.1
==> default: Successfully installed trollop-2.1.2
==> default: Successfully installed gauntlt-1.0.10
==> default:
==> default: Successfully installed bundler-1.9.9
==> default:
==> default: Building native extensions.  This could take a while...
==> default:
==> default: Building native extensions.  This could take a while...
==> default:
==> default: Building native extensions.  This could take a while...
==> default:
==> default: 16 gems installed
==> default:
==> default: Installing ri documentation for builder-3.2.2...
==> default:
==> default: Installing ri documentation for diff-lcs-1.2.5...
==> default:
==> default: Installing ri documentation for multi_json-1.11.0...
==> default:
==> default: Installing ri documentation for gherkin-2.12.2...
==> default:
==> default: Installing ri documentation for multi_test-0.1.2...
==> default:
==> default: Installing ri documentation for cucumber-1.3.15...
==> default:
==> default: Installing ri documentation for ffi-1.9.8...
==> default:
==> default: Installing ri documentation for childprocess-0.5.6...
==> default:
==> default: Installing ri documentation for rspec-support-3.2.2...
==> default:
==> default: Installing ri documentation for rspec-expectations-3.2.1...
==> default:
==> default: Installing ri documentation for aruba-0.5.4...
==> default:
==> default: Installing ri documentation for mini_portile-0.5.3...
==> default:
==> default: Installing ri documentation for nokogiri-1.6.1...
==> default:
==> default: Installing ri documentation for trollop-2.1.2...
==> default:
==> default: Installing ri documentation for gauntlt-1.0.10...
==> default:
==> default: Installing ri documentation for bundler-1.9.9...
==> default:
==> default: Installing RDoc documentation for builder-3.2.2...
==> default:
==> default: Installing RDoc documentation for diff-lcs-1.2.5...
==> default: Installing RDoc documentation for multi_json-1.11.0...
==> default: Installing RDoc documentation for gherkin-2.12.2...
==> default: Installing RDoc documentation for multi_test-0.1.2...
==> default: Installing RDoc documentation for cucumber-1.3.15...
==> default: Installing RDoc documentation for ffi-1.9.8...
==> default: Installing RDoc documentation for childprocess-0.5.6...
==> default: Installing RDoc documentation for rspec-support-3.2.2...
==> default: Installing RDoc documentation for rspec-expectations-3.2.1...
==> default: Installing RDoc documentation for aruba-0.5.4...
==> default: Installing RDoc documentation for mini_portile-0.5.3...
==> default: Installing RDoc documentation for nokogiri-1.6.1...
==> default: Installing RDoc documentation for trollop-2.1.2...
==> default: Installing RDoc documentation for gauntlt-1.0.10...
==> default: Installing RDoc documentation for bundler-1.9.9...
==> default: STDERR: ERROR:  Error installing arachni:
==> default:    arachni requires Ruby version >= 2.0.0.
==> default: ---- End output of /usr/bin/ruby -S gem install gauntlt bundler arachni ----
==> default: Ran /usr/bin/ruby -S gem install gauntlt bundler arachni returned 1
==> default:
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef/9f0a5a37352ff7848058be768a28347a/cookbooks/vagrant_main/recipes/default.rb
==> default:
==> default:  32: execute "install gems" do
==> default:  33:   command "/usr/bin/ruby -S gem install gauntlt bundler arachni"
==> default:  34: end
==> default:  35:
==> default:
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef/9f0a5a37352ff7848058be768a28347a/cookbooks/vagrant_main/recipes/default.rb:32:in `from_file'
==> default:
==> default: execute("install gems") do
==> default:   action "run"
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :execute
==> default:   command "/usr/bin/ruby -S gem install gauntlt bundler arachni"
==> default:   backup 5
==> default:   returns 0
==> default:   declared_type :execute
==> default:   cookbook_name :vagrant_main
==> default:   recipe_name "default"
==> default: end
==> default:
==> default: [2015-05-20T23:25:36+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2015-05-20T23:25:36+00:00] ERROR: Running exception handlers
==> default: [2015-05-20T23:25:36+00:00] ERROR: Exception handlers complete
==> default: [2015-05-20T23:25:36+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-05-20T23:25:36+00:00] ERROR: execute[install gems](vagrant_main::default line 32) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of /usr/bin/ruby -S gem install gauntlt bundler arachni ----
==> default: STDOUT: Building native extensions.  This could take a while...
==> default: Building native extensions.  This could take a while...
==> default: Building native extensions.  This could take a while...
==> default: Successfully installed builder-3.2.2
==> default: Successfully installed diff-lcs-1.2.5
==> default: Successfully installed multi_json-1.11.0
==> default: Successfully installed gherkin-2.12.2
==> default: Successfully installed multi_test-0.1.2
==> default: Successfully installed cucumber-1.3.15
==> default: Successfully installed ffi-1.9.8
==> default: Successfully installed childprocess-0.5.6
==> default: Successfully installed rspec-support-3.2.2
==> default: Successfully installed rspec-expectations-3.2.1
==> default: Successfully installed aruba-0.5.4
==> default: Successfully installed mini_portile-0.5.3
==> default: Successfully installed nokogiri-1.6.1
==> default: Successfully installed trollop-2.1.2
==> default: Successfully installed gauntlt-1.0.10
==> default: Successfully installed bundler-1.9.9
==> default: Building native extensions.  This could take a while...
==> default: Building native extensions.  This could take a while...
==> default: Building native extensions.  This could take a while...
==> default: 16 gems installed
==> default: Installing ri documentation for builder-3.2.2...
==> default: Installing ri documentation for diff-lcs-1.2.5...
==> default: Installing ri documentation for multi_json-1.11.0...
==> default: Installing ri documentation for gherkin-2.12.2...
==> default: Installing ri documentation for multi_test-0.1.2...
==> default: Installing ri documentation for cucumber-1.3.15...
==> default: Installing ri documentation for ffi-1.9.8...
==> default: Installing ri documentation for childprocess-0.5.6...
==> default: Installing ri documentation for rspec-support-3.2.2...
==> default: Installing ri documentation for rspec-expectations-3.2.1...
==> default: Installing ri documentation for aruba-0.5.4...
==> default: Installing ri documentation for mini_portile-0.5.3...
==> default: Installing ri documentation for nokogiri-1.6.1...
==> default: Installing ri documentation for trollop-2.1.2...
==> default: Installing ri documentation for gauntlt-1.0.10...
==> default: Installing ri documentation for bundler-1.9.9...
==> default: Installing RDoc documentation for builder-3.2.2...
==> default: Installing RDoc documentation for diff-lcs-1.2.5...
==> default: Installing RDoc documentation for multi_json-1.11.0...
==> default: Installing RDoc documentation for gherkin-2.12.2...
==> default: Installing RDoc documentation for multi_test-0.1.2...
==> default: Installing RDoc documentation for cucumber-1.3.15...
==> default: Installing RDoc documentation for ffi-1.9.8...
==> default: Installing RDoc documentation for childprocess-0.5.6...
==> default: Installing RDoc documentation for rspec-support-3.2.2...
==> default: Installing RDoc documentation for rspec-expectations-3.2.1...
==> default: Installing RDoc documentation for aruba-0.5.4...
==> default: Installing RDoc documentation for mini_portile-0.5.3...
==> default: Installing RDoc documentation for nokogiri-1.6.1...
==> default: Installing RDoc documentation for trollop-2.1.2...
==> default: Installing RDoc documentation for gauntlt-1.0.10...
==> default: Installing RDoc documentation for bundler-1.9.9...
==> default: STDERR: ERROR:  Error installing arachni:
==> default:    arachni requires Ruby version >= 2.0.0.
==> default: ---- End output of /usr/bin/ruby -S gem install gauntlt bundler arachni ----
==> default: Ran /usr/bin/ruby -S gem install gauntlt bundler arachni returned 1
==> default: [2015-05-20T23:25:36+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by mclebaron** [comment]
I'm still having this issue in 2017, was there any sort of ultimate resolution?

==> default: Gem files will remain installed in /var/lib/gems/1.9.1/gems/concurrent-ruby-ext-1.0.0 for inspection.
==> default: Results logged to /var/lib/gems/1.9.1/gems/concurrent-ruby-ext-1.0.0/ext/concurrent/gem_make.out
==> default: ---- End output of /usr/bin/ruby -S gem install gauntlt bundler arachni ----
==> default: Ran /usr/bin/ruby -S gem install gauntlt bundler arachni returned 1
==> default: [2017-01-25T19:55:45+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
